/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        'primary-container': 'var(--primary-container)',
        primaryRGB: 'var(--primary-rgb)',
        surface: ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        surfaceRGB: 'var(--surface-rgb)',
        'surface-container-low': ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        surfaceContainerLowRGB: 'var(--surface-container-low-rgb)',
        'surface-container': ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        surfaceContainerRGB: 'var(--surface-container-rgb)',
        'surface-container-lowest': ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        surfaceContainerLowestRGB: 'var(--surface-container-lowest-rgb)',
        'surface-container-high': ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        surfaceContainerHighRGB: 'var(--surface-container-high-rgb)',
        background: ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        'on-surface': ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        onSurfaceRGB: 'var(--on-surface-rgb)',
        'on-surface-variant': ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        onSurfaceVariantRGB: 'var(--on-surface-variant-rgb)',
        tertiary: ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        tertiaryRGB: 'var(--tertiary-rgb)',
        'tertiary-container': 'var(--tertiary-container)',
        outline: ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        outlineRGB: 'var(--outline-rgb)',
        'outline-variant': ({ rgb }) => `rgba(${rgb}, var(--tw-opacity, 1))`,
        outlineVariantRGB: 'var(--outline-variant-rgb)',
        error: '#dc2626',
        success: '#16a34a',
      },
      fontFamily: {
        display: ['Inter', 'PingFang SC', 'Noto Sans SC', 'sans-serif'],
        body: ['Inter', 'PingFang SC', 'Noto Sans SC', 'sans-serif'],
      },
      spacing: {
        '18': '4.5rem',
        '24': '6rem',
      },
      borderRadius: {
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
